### ISSUE TITLE
Add car park specs

### ISSUE THREAD

**Issue by nighthawk** [skedgo/TSP-APIs#2]
Please add specs for car parks to this repo. They are already implemented by https://github.com/skedgo/de-nuremberg-api.

**Comment by fersagui** [comment]
I have added the car-share.swagger.yaml. [View in Swagger UI](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/skedgo/TSP-APIs/master/car-park.swagger.yaml)

**Comment by nighthawk** [comment]
Thanks!
